# Predictive Modeling Configuration

# Data Settings
data:
  random_state: 42
  test_size: 0.2
  validation_size: 0.1
  max_features: 1000
  min_samples: 10

# Model Parameters
models:
  # Classification Models
  classification:
    logistic_regression:
      C: 1.0
      max_iter: 1000
      random_state: 42
    
    random_forest:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      random_state: 42
    
    xgboost:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      random_state: 42
    
    lightgbm:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      random_state: 42
    
    svm:
      C: 1.0
      kernel: 'rbf'
      gamma: 'scale'
      random_state: 42

  # Regression Models
  regression:
    linear_regression:
      fit_intercept: true
    
    ridge:
      alpha: 1.0
      fit_intercept: true
    
    lasso:
      alpha: 1.0
      fit_intercept: true
    
    elastic_net:
      alpha: 1.0
      l1_ratio: 0.5
      fit_intercept: true

  # Clustering Models
  clustering:
    kmeans:
      n_clusters: 3
      random_state: 42
      max_iter: 300
    
    dbscan:
      eps: 0.5
      min_samples: 5
    
    hierarchical:
      n_clusters: 3
      linkage: 'ward'

  # Deep Learning Models
  deep_learning:
    neural_network:
      hidden_layers: [64, 32, 16]
      activation: 'relu'
      dropout_rate: 0.2
      learning_rate: 0.001
      batch_size: 32
      epochs: 100
    
    lstm:
      units: 50
      dropout: 0.2
      recurrent_dropout: 0.2
      batch_size: 32
      epochs: 100

  # Time Series Models
  time_series:
    prophet:
      changepoint_prior_scale: 0.05
      seasonality_prior_scale: 10.0
      holidays_prior_scale: 10.0
    
    arima:
      order: [1, 1, 1]
      seasonal_order: [1, 1, 1, 12]

# Training Settings
training:
  cv_folds: 5
  scoring:
    classification: 'accuracy'
    regression: 'neg_mean_squared_error'
    clustering: 'silhouette'
  
  hyperparameter_tuning:
    n_trials: 100
    timeout: 3600  # 1 hour

# Evaluation Metrics
evaluation:
  classification:
    - 'accuracy'
    - 'precision'
    - 'recall'
    - 'f1'
    - 'roc_auc'
  
  regression:
    - 'mse'
    - 'mae'
    - 'r2'
    - 'explained_variance'
  
  clustering:
    - 'silhouette_score'
    - 'calinski_harabasz_score'
    - 'davies_bouldin_score'
  
  time_series:
    - 'mape'
    - 'rmse'
    - 'mae'

# Visualization Settings
visualization:
  style: 'seaborn-v0_8'
  figsize: [10, 6]
  dpi: 300
  save_format: 'png'
  color_palette: 'viridis'

# Logging
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: 'logs/predictive_modeling.log'

# Output Settings
output:
  models_dir: 'models/saved'
  results_dir: 'results'
  reports_dir: 'reports'
  cache_dir: 'cache'
